
class Constants
	LVM = "logical"
	HYPERVISOR_TYPE = "xen"
	KERNEL = "/boot/vmlinuz-2.6.26-1-xen-amd64"
	INITRD = "/boot/initrd.img-2.6.26-1-xen-amd64"
	CMDLINE = "root=/dev/sda2 ro ip=:1.2.3.4::::eth0:dhcp xencons=tty"
	DESTROY = "destroy"
	RESTART = "restart"
	DISK_TYPE = "block"
	DISK_DEVICE = "disk"
	DRIVER_NAME = "phy"
	BUS_TYPE = "scsi"
	CLOCK_OFFSET_UTC = "utc"
	CLOCK_OFFSET_LOCALTIME = "localtime"
	TARGET_DEVICE_SWAP = "sda1"
	TARGET_DEVICE_ROOT = "sda2"
	INTERFACE_TYPE = "bridge"
	INTERFACE_DEVICE = "vif1.0"
	CONSOLE_TYPE = "pty"
	CONSOLE_TTY = "/dev/pts/0"
	CONSOLE_TARGET_PORT = "0"
	PERMISSIONS_MODE = "060660"
	PERMISSIONS_OWNER = "0"
	PERMISSIONS_GROUP = "6"
end